[versions]
spring-boot = "3.5.7"
kotlin = "2.2.21"
integration-test = "2.2.5"
jspecify = "1.0.0"
groovy = "4.0.29"
spock = "2.3-groovy-4.0"

[libraries]
spring-boot-dependencies = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }
groovy = { group = "org.apache.groovy", name = "groovy", version.ref = "groovy" }
spock-core = { group = "org.spockframework", name = "spock-core", version.ref = "spock" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
integration-test = { id = "com.coditory.integration-test", version.ref = "integration-test" }
